[tool.commitizen]
gpg_sign = true
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "pep440"
version = "2025.12.0"
update_changelog_on_bump = true
version_files = [
  "src/incendium/__about__.py:__version__",
  "stubs/pyproject.toml:version"
]
